### ISSUE TITLE
[Help wanted] I want options to place comments like XCTAssertEqual(A, B, "Comment") on a separate line

### ISSUE THREAD

**Issue by psbss** [giginet/swift-testing-revolutionary#12]
Hi giginet!
I have a ideas to improve this great tools.

## Details

In XCTAssertEqual, it is possible to pass a comment as the third argument, but after converting to SwiftTesting, you can achieve the same display on error by placing the comment on the line above #expect.
This method is more readable and reduces the amount of code on a single line, which is why it is highly valued in our project. 

Would it be possible to provide an option to convert in this way?

## Sample code
original code
```swift
func test_is_success() {
    vm.successs()
    XCTAssertEqual(vm.state.state, "success", "成功していること")
}
```

after run tool
```swift
@Test
func is_success() {
    vm.successs()
    // 成功していること
    #expect(vm.state.state == "success")
}
```

**Comment by giginet** [comment]
This conversion is not common so it should not be implemented.

However, we can take the second argument of `#expect` and I thought I implemented this conversion 🤔 
https://developer.apple.com/documentation/testing/expect(_:_:sourcelocation:) 

I'll check the situation!

**Comment by giginet** [comment]
I confirmed this conversion works well. We already have a test case, but I added comments to the fixtures.

https://github.com/giginet/swift-testing-revolutionary/blob/main/Tests/RevolutionKitTests/AssertionsTests.swift#L171-L178

**Comment by giginet** [comment]
I'll close this issue, but if you find a situation in which this conversion doesn't work well, feel free to open a new issue.
