### ISSUE TITLE
Crash when running tests

### ISSUE THREAD

**Issue by maartene** [giginet/swift-testing-revolutionary#5]
Hi!

When I run the tests in Xcode-beta / Swift 6, I get the following crash:
`Thread 3: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=257 "Het bestand 'Inputs' kon niet worden geopend, omdat je geen bevoegdheden hebt om het te bekijken." UserInfo={NSUserStringVariant=(`

<img width="2032" alt="Screenshot of crash " src="https://github.com/giginet/swift-testing-revolutionary/assets/5150271/bb6772e5-2712-4ab6-a701-c9cc949b03f9">

Unfortunately, I can't see which test triggers this.

Kind regards,

Maarten

**Comment by giginet** [comment]
Thank you, I'll check this later.

Additionally, we don't run tests for Xcode 16 beta on GitHub Action, so I'll prepare a CI environment to run tests for Swift 6.

**Comment by giginet** [comment]
Umm, I can't reproduce this issue on my environment with 16 beta 2.

How about modifying `SwiftTestingBridge.swift`?

```swift
#if compiler(<6.0)

// Below Xcode 15.x, we can't run swift-testing directly. I believe it will be unnecesarry since Xcode 16.
final class AllTests: XCTestCase {
    func testAll() async {
        await XCTestScaffold.runAllTests(hostedBy: self)
    }
}

#endif
```

This bridging is not required for Xcode 16 and Swift 6 compiler.

**Comment by giginet** [comment]
I guess your repository is in a not readable/writable path

**Comment by maartene** [comment]
its kinda weird: I gave Xcode-beta full disc access. And also tried with the repo in a different path. 
Might very well be an Xcode-beta bug though. I'm going to try if I can run the tests somewhere else.

**Comment by giginet** [comment]
Could you see the full path of the error message?

According to the screenshot, `Operation is not permitted`. RevolutionaryKitTests read fixtures from a file system, but It seems to be failed.

**Comment by maartene** [comment]
Just tried running the tests after moving the repo to /tmp . Now the tests run correctly. 
I'm writing this one up to an Xcode bug. So I'll create a feedback message for Apple.

**Comment by maartene** [comment]
FYI: it seems this is fixed in the new Xcode beta 3.
