### ISSUE TITLE
Allow removal of other prefixes (i.e. 'test_') as part of the run

### ISSUE THREAD

**Issue by maartene** [giginet/swift-testing-revolutionary#7]
Hi,

I tend to use `test_<very wordy test name>` to prefix XCTest tests. Running the tool leads to all my test now being called:
`@Test _<testname>` 

<img width="196" alt="Scherm­afbeelding 2024-07-18 om 10 25 58" src="https://github.com/user-attachments/assets/f7db1e74-fb75-40dc-8372-b3ff3c5ebdfe">

Would be nice if there was an option to get rid of that first underscore while running the tool. Or perhaps pass in a prefix to remove?

Note: this is a minor issue. Manually getting rid of the underscores isn't a lot of work. 

KR Maarten

**Comment by giginet** [comment]
Your point makes sense. 
This tool assumes that test methods are named in camelCase; you may want to consider addressing snake_case as well.
For now, it makes sense to apply a special conversion to naming with `test_` prefix.

I'll support this.

**Comment by psbss** [comment]
I was just thinking the same thing, thank you.

**Comment by giginet** [comment]
This feature was available since 0.3.0🎉
